language: go

addons:
  apt:
    packages:
      - build-essential
      - libx11-dev
      - libxcursor-dev
      - xbitmaps
      - libxmu-headers
      - imlib2-dev
      - xinerama-dev

go:
    - "1.11"
    - "1.12"
    - "1.13"
